#!/usr/bin/env perl

use 5.18.0;
use strict;

use Data::Dumper  qw( Dumper );

open my $a, 'versions';

chomp(my @a=<$a>);
my %a=map split(/\t+/,$_,2),@a;

while (<>) {
  s/\b([\w-]+?)((-\d+)*)(?=[ ,]|$)/exists $a{$1} ? "$1-$a{$1}" : "$1$2"/eg;
  print;
}